accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns =[
path('',views.home,name= "home"),
path('signup',views.signup_views, name ="signup" ),
path('login',views.login_views, name ="login"),
path('logout',views.logout_views,name ="logout"  ),
]

articles/urls.py
from django.urls import path
from . import views

app_name = "a31"
urlpatterns = [
    path('',views.articles_list, name ="a3" ),
    path('create',views.create_article,name ="create" ),
    path('<slug>',views.amir_detail, name = "a2"),
    # path('about/', views.about,name = "about"),

]

djangoBlog/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about,name = "about"),
    path('',views.home),
    path('articles/',include('articles.urls')),
    path('accounts/',include('accounts.urls')),

]

# urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    # ... the rest of your URLconf goes here ...
 # static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # ... the rest of your URLconf goes here ...

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models


class Article(models.Model):
    titel = models.CharField(max_length = 100)
    slug =models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    imag = models.ImageField(default='default.jpg',blank=True )


    def __str__(self):
        return self.titel

    def snippet(self):
        return self.body[0:35] + '.....'

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout


def home(request):
    return render(request, 'accounts/homee.html')


def signup_views(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
        form = UserCreationForm()
    return render(request,'accounts/signup.html',{'form':form})

def login_views(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # login_views
            user = form.get_user()
            login(request,user)
            if "next" in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('a31:a3')


    else:
        form = AuthenticationForm()
        return render(request,'accounts/login.html',{'form':form})




def logout_views(request):
    if request.method == 'POST':
        logout(request)

        return redirect('a31:a3')

articles/views.py
from django.shortcuts import render,HttpResponse
from.import models
from django.contrib.auth.decorators import login_required


def articles_list(request):
    articles = models.Article.objects.all().order_by('-date')

    args = {'articles':articles}
    return render(request,'articles/articleslist.html',args)


def amir_detail(request,slug):
    # return HttpResponse(slug)
    article = models.Article.objects.get(slug=slug)
    return render(request,'articles/article_detail.html',{'article':article})


@login_required(login_url = 'accounts/login')
def create_article(request):
    return render(request,'articles/create_articles.html' )

djangoBlog/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse

def about(request):
    return render(request,'about.html')

def home(request):
    return render(request,'home.html')

    return HttpResponse('home')

def sst(request):
    return HttpResponse ('avalbad')

accounts/templates/accounts/homee.html
{% extends 'base.html' %}
{% csrf_token %}


{% block title %}
   <h1>accounts</h1>
{% endblock %}

{% block content %}
 <header>
   <nav>
     <ul>
      <li> <a href="{% url 'accounts:signup' %}" class="active">SIG NUP</a> </li>
     <li> <a href="{% url 'accounts:login' %}" class="active">LOG IN</a> </li>
    </ul>
   </nav>
 </header>

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html'%}


{% block cont %}
<h1>login</h1>
<form class="" action= "{% url 'accounts:login' %}" method="post">
  {{form}}
  {% csrf_token %}
  {% if request.GET.next %}
   <input type="hidden" name="next" value="{{request.GET.next}}">
  {% endif %}
  <input type="submit"  value="login">
</form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html'%}


{% block cont %}
<h1>sign up</h1>
<form class="site_form" action="{% url 'accounts:signup' %}" method="post">
  {{form}}
  {% csrf_token %}
  <input type="submit"  value="submit">
</form>
{% endblock %}

articles/templates/articles/article_detail.html
{%extends 'base.html'%}

{% block cont %}
<div class="article_detail">
  <div class="article">
    <img src="{{ 'article.image.url' }}" alt="assets">
      <h2>{{article.titel}}</h2>
      <p>{{article.body}}</p>
      <p>{{article.date}}</p>
  </div>
</div>
{% endblock %}

articles/templates/articles/articleslist.html
{% extends 'base.html' %}

{%block title %}
Aticles
{%endblock%}
{% block cont %}
<div class="container">
<h1>articles list</h1>
{% for article in articles %}
<h2><a href="{% url 'a31:a2' slug=article.slug %}">{{article.titel}}</a></h2>
<p>{{article.snippet}}</p>
<p>{{article.date}}</p>
{% endfor %}
</div>
{%endblock%}

articles/templates/articles/create_articles.html
{% extends 'base.html' %}



{% block cont %}
<div class="create_article">
  <h1> create your articles
  </h1

</div>
{% endblock %}

templates/about.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>about</title>
  </head>
  <body>
<h1>about</h1>
<p> ما جنگو را دوست نداریم </p>
  </body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
  <title>
   {% block titel %}

   {%endblock%}
  </title>
<link rel="stylesheet" href="{%static 'styles.css' %}"></head>
<body>
  <h2> <a href="{% url 'a31:a3' %}">LOGO</a> </h2>
  <nav>
    <ul>
      <li>
        <form class="logout_like" action="{% url 'accounts:logout' %}" method="post">
          {% csrf_token %}
          <button type="submit" name="">logout</button>

        </form>
      </li>
    </ul>
  </nav>
   {% block cont %}

   {% endblock %}
</body>
 </html>

templates/home.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>home</title>
  </head>
  <body>
<h1>home</h1>
<p>welcome too my bloge</p>
    <header>
        <nav>
            <div class="logo">
              <a href="#">portfolio.</a>
            </div>
            <ul>
                <li> <a href="{% url 'accounts:login' %}" class="active">Home</a> </li>
                <li> <a href="#" class = "active">about</a></li>
                <li> <a href="accounts#homee.html">accounts</a></li>
                <li> <a href="#">portfolio</a></li>
                <li> <a href="#">contact</a></li>
            </ul>
            <div class="button">
                <button> <a href="#"></a>Sign Up</button>
                <!-- <button>Log In</button> -->
                <button><a href="#"></a>LOG IN</button>
            </div>
        </nav>
    </header>
  </body>
  <style>
        @import url('djangoBlog\media\2.jpg')
</html>